### ISSUE TITLE
Steps for Bulkrax readiness for Hyku 6 and Hyrax 4 & 5

### ISSUE THREAD

**Issue by jeremyf** [samvera/bulkrax#897]
This builds from the `hyrax-4-valkyrie-support` branch, and assumes that the branch works given that GBH has used the branch in production.

Contributes to:
- https://github.com/scientist-softserv/hykuup_knapsack/issues/86

These steps should get us to a "user functional" state of Bulkrax and IiifPrint, which we can then begin further testing of Hyku.

- [x]  Move transactions out of initializer; create tests (akin to IiifPrint’s tests) to demonstrate the step composition.
  a. Convert the `create_with_bulk_behavior` and `update_with_bulk_behavior` to a constant; that way we can reference it in IiifPrint and document the “magic” string.
- [x]  Update IiifPrint to sniff out if Bulkrax has a transaction for `update_with_bulk_behavior` and `create_with_bulk_behavior` (check if the constants are defined); then inject accordingly.
  - Update:  create_with_bulk_behavior is not needed for iiif_print
- [x] Address TODOs (`git diff main..hyrax-4-valkyrie-support | rg TODO`)
  - [x]  TODO: uncomment when we upgrade Hyrax 4.x
     - How can we handle both Hyrax 4.x and Hyrax 3.x versions?  Note IiifPrint has gem version sniffing examples `if Gem::Version.new(Hyrax::VERSION) >= Gem::Version.new('4.0.0')`
  - [x] TODO: What other fields are necessary: %i[id edit_users edit_groups read_groups work_members_attributes]?
      - We probably want to add the above array to the code.
  - [x] TODO: there has got to be a better way. Only array types have 'of'
      - Punt, but if it comes to you...
  - [x] TODO: move outside of initializer?
      - Do it, so we can write tests and have a place for constants that IiifPrint can work through.
  - [x] TODO: uninitialized constant BulkraxTransactionContainer::InlineUploadHandler
      - We'll need to be mindful of 
- [x] Specs should pass
  - [x] Reconcile HasMatchers with HasMappingExt. (get rid of HasMappingExt and make `multiple?` work for both Valkyrie and ActiveFedora). 
    - [x] **diffs**: #field_supported?, #multiple?, #multiple_field?, #ar_multiple?, #valkyrie_multiple?, #schema_form_definitions
  - [x] Make sure specs works for both Valkyrie resources (Bulkrax::ValkyrieObjectFactory) and Active Fedora

Remember, Hyrax must be optional dependency.  There are implementations that don't rely on Hyrax.

**Comment by ShanaLMoore** [comment]
GBH bulkrax sha: c2ee9bc
