### ISSUE TITLE
"Bulkrax identifier" custom queries & behavior doesn't belong in Hyku

### ISSUE THREAD

**Issue by laritakr** [samvera/bulkrax#903]
Hyku has some added custom queries and conditional indexing of "bulkrax_identifier", which belong in bulkrax. The term doesn't exist on the models, so including queries and indexing isn't happing in the right place. 

This code should be included in Bulkrax as part of the Valkyrization process, and removed from Hyku.

Relevant modules:
- collection_indexer.rb & collection_resource_identifier.rb
- hyku_indexing.rb
- find_by_bulkrax_identifier.rb (app/services/hyrax/custom_queries/ and app/services/wings/custom_queries/)
- find_by_bulkrax_identifier_spec.rb

Use of the term, such as adding it to models and mapping it, should also be considered and documented. 

related: 
- https://github.com/scientist-softserv/hykuup_knapsack/issues/136

**Comment by ShanaLMoore** [comment]
done ✅
