### ISSUE TITLE
importer tries, fails to create FileSets before Works are persisted (tested in 5.5.1, 7.0.0)

### ISSUE THREAD

**Issue by aploshay** [samvera/bulkrax#955]
Behavior occurs running [this branch of essi](https://github.com/IU-Libraries-Joint-Development/essi/tree/essi-875_bulkrax_upgrade), with bulkrax 5.5.0:
* on the first run of an importer, all the FileSet imports fail with error:
```
NoMethodError - undefined method `permissions' for nil:NilClass
```
which occurs because a nil value is returned for `work` by `find_record` called in `create_file_set`, since apparently the work hasn't been persisted yet.  All the work imports do, however, succeed.
* on the second run of that same importer (running with "Update metadata and replace files"), all the FileSet records do import, because now the parent works are persisted and found.

I've also tested bulkrax 7.0.0 -- the same issue occurs on the first run, but the second run now also fails to import FileSet records.

I'm surprised that it's possible for the Work, FileSet creation sequencing to get flipped around somehow -- any notions of what could be causing this?

**Comment by bkiahstroud** [comment]
1. Which parser are you using? CSV, etc. 
2. If CSV, how are the files being imported? Does each FileSet have its own row, or are the files listed in a column on the work's row?

**Comment by aploshay** [comment]
1. CSV
2. Each FileSet  in its own row -- [Method 2](https://github.com/samvera/bulkrax/wiki/CSV-Importer#method-2)

**Comment by kirkkwang** [comment]
Hi @aploshay, I added this [commit](https://github.com/samvera/bulkrax/commit/0de8ee06115ff9e6e89177d93c407826ae892a7f) which worked for me, however, I'm seeing different results in other applications which could be a configuration issue.  Do you mind give main a try?

**Comment by bkiahstroud** [comment]
This ticket _might_ be related to this other one:
- https://github.com/samvera/bulkrax/issues/953

**Comment by kirkkwang** [comment]
That's great to hear @aploshay ! Do you think we can close this issue now?

**Comment by aploshay** [comment]
@kirkkwang I believe so, thanks
