### ISSUE TITLE
Sorting importers by "Last Run" brings up a DataTables alert, does not change order.

### ISSUE THREAD

**Issue by lsat12357** [samvera/bulkrax#956]
On the importers index page, clicking on "Last Run" brings up a DataTables alert box with the following message:
DataTables warning: table id=importers-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

In the console, there is an ActiveRecord error:
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "last_imported_at" does not exist
...
SELECT  "bulkrax_importers".* FROM "bulkrax_importers" ORDER BY last_imported_at asc

**Comment by kirkkwang** [comment]
@lsat12357 We recently made a fix with this PR just FYI.  It's working on our end but if you have the means would you be able to test it out?  You would need to update and run migrations.

https://github.com/samvera/bulkrax/pull/977

**Comment by lsat12357** [comment]
@kirkkwang apologies, did not catch the notification on this. I just tried it and yes the importer index is working for me too, thanks!
